### ISSUE TITLE
You already have a Gem request in.

### ISSUE THREAD

**Issue by kilroy79763** [patri0t86/ACManager#37]
Maybe I am missing something.  The bot will not open gems\ portals and was opening them before.
give the message You already have a Gem request in.

**Comment by patri0t86** [comment]
What led up to this event/getting stuck in this way? I'm not sure if you have any context (due to this being an unattended bot) that could help give some insight?

Did you restart the bot/relog the client, or try anything in particular that might help diagnose?

**Comment by kilroy79763** [comment]
Hello Patrick,The only thing I know that I did was move it from one computer to another.How ever after the move it was working properly.I tried everything you mentioned and more that i probably forgot.I ended up reinstalling and of course redefining all the portals. It seems like maybe an xml file got messes up after I moved and like I said it was working.So not sure what happened.Is there a way to back up the configs...so if it messes up again I can just restore them from a backup?I "think?" I still have the old files if you want to look at those for future diagnosis to others.I also want to say thank you it is a good bot and has plenty of features.I also run an IBAirport bot in shoushi and another one I think on Coldeve. You all rock - thanks for all you do for the AC community.Any way thank youAl Forte


-------- Original Message --------
Subject: Re: [patri0t86/ACManager] You already have a Gem request in.
(#37)

**Comment by patri0t86** [comment]
Oh, definitely back it up if you can - can save time moving it from machine to machine (I've done it a few times myself changing VMs). 

The config that is most important is the `acm_settings.xml` file located in the folder for that account, for that server. To handle running multiple bots on the same machine, I have it separated that way. There is an ACManager folder adjacent to where to installed ACManager.dll where all of this is located. All information is stored in XML format, so it is human readable/editable outside of the game as well. If you wish to back that file up to save future configs, just keep a copy located outside of the ACManager folder that was created when you installed the plugin.

If a file is corrupt, you will get a warning when you log into the game saying the file is corrupt, or something along the lines of "XML error". I have only seen or had it reported that this occurs when a VM or machine is hard-powered down improperly. The file isn't saved in proper format when this occurs. The workaround is to open the file in an editor and save it again, no change necessary. This resets the file and works again. Do that for all of the XML files (not the buff profiles), and they should just work again.

And you're very welcome for the bot! I've worked very hard on it and I'm the only dev that has touched it, so I put a lot of care into it!

I'm going to mark this issue closed since it appears it is fixed.
